version: "2.0"
services:
  pg:
    image: postgres:10
    volumes:
      - ./data/pgdata/db:/var/lib/postgresql/data
      - ./data/pgdata/etc:/etc/postgresql
      - ./data/pgdata/logs:/var/log/postgresql
    restart:
      always
  app:
    build: .
    volumes:
      - ./app:/opt/app
      - ./dependencies:/opt/dependencies
      - ./media:/opt/static/media
      - ./static:/opt/static/static
      - ./CHANGELOG.md:/opt/CHANGELOG.md
    links:
      - pg:pg
    ports:
      - 8002:8000
    env_file:
      - .env
  uwsgi:
    build: .
    depends_on:
      - "pg"
    volumes:
      - ./app:/opt/app
      - ./dependencies:/opt/dependencies
      - ./media:/opt/static/media
      - ./static:/opt/static/static
      - ./logs:/srv/logs
      - ./CHANGELOG.md:/opt/CHANGELOG.md
    env_file:
      - .env
    command:
      bash /docker_entrypoint.sh
    restart:
      always
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - uwsgi
    volumes_from:
      - uwsgi
    volumes:
      - ./logs:/nginx/logs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart:
      always
