# Generated by Django 2.2.6 on 2019-10-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20191008_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_page', models.PositiveIntegerField()),
                ('exit_page', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('On Stage', 'On Stage'), ('Off Stage', 'Off Stage')], default='On Stage', max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Character')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Scene')),
            ],
        ),
    ]
