# Generated by Django 2.2.6 on 2019-10-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='start_date',
            field=models.DateField(),
        ),
    ]
