# Generated by Django 2.2.6 on 2019-10-08 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20191008_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='show',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='show.Show'),
            preserve_default=False,
        ),
    ]
