# Generated by Django 2.2.6 on 2019-10-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['start_page', 'end_page', 'name']},
        ),
    ]
