# Generated by Django 2.2.6 on 2019-10-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_auto_20191008_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['lib_start_page', 'lib_end_page', 'name']},
        ),
    ]
