# Generated by Django 2.2.6 on 2019-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0009_auto_20191008_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='ensemble_characters',
            field=models.ManyToManyField(blank=True, related_name='ensemble_songs', to='show.Character'),
        ),
        migrations.AddField(
            model_name='song',
            name='featured_characters',
            field=models.ManyToManyField(blank=True, related_name='featured_songs', to='show.Character'),
        ),
    ]
