# Generated by Django 2.2.6 on 2019-10-08 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0011_charactergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='character_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='show.CharacterGroup'),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('character', 'Character'), ('group', 'Group')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='show',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='show.Show'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='show.Character'),
        ),
    ]
