# Generated by Django 2.2.6 on 2019-10-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0012_auto_20191009_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='ensemble_groups',
            field=models.ManyToManyField(blank=True, related_name='ensemble_group_songs', to='show.CharacterGroup'),
        ),
        migrations.AddField(
            model_name='song',
            name='featured_group',
            field=models.ManyToManyField(blank=True, related_name='featured_group_songs', to='show.CharacterGroup'),
        ),
    ]
