# Generated by Django 2.2.6 on 2019-10-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0013_auto_20191009_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='featured_group',
            new_name='featured_groups',
        ),
    ]
