# Generated by Django 2.2.6 on 2019-10-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0014_auto_20191009_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['show', 'start_page', 'end_page', 'name']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['show', 'lib_start_page', 'lib_end_page', 'name']},
        ),
    ]
