# Generated by Django 2.2.6 on 2019-10-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0015_auto_20191009_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='speaks',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.CharField(choices=[('On Stage', 'On Stage'), ('Off Stage', 'Off Stage Voice/Action')], default='On Stage', max_length=255),
        ),
    ]
