# Generated by Django 2.2.6 on 2019-10-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0016_auto_20191010_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactertype',
            options={'ordering': ['ordering_preference', 'name']},
        ),
        migrations.AddField(
            model_name='charactertype',
            name='ordering_preference',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
