# Generated by Django 2.2.6 on 2019-10-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0017_auto_20191010_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['show', 'character_type__ordering_preference', 'name']},
        ),
    ]
