# Generated by Django 2.2.6 on 2019-10-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0018_auto_20191012_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['show', 'character_type__ordering_preference', 'billing_order', 'name']},
        ),
        migrations.AddField(
            model_name='character',
            name='billing_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
