# Generated by Django 2.2.6 on 2019-10-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0019_auto_20191012_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='billing_order',
            field=models.IntegerField(default=1),
        ),
    ]
