# Generated by Django 2.2.6 on 2019-10-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0020_auto_20191012_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['show', 'enter_page', 'page_offset']},
        ),
        migrations.AddField(
            model_name='entry',
            name='cue_line',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='page_offset',
            field=models.IntegerField(default=0),
        ),
    ]
