# Generated by Django 2.2.6 on 2019-10-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0021_auto_20191013_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertype',
            name='could_use_microphone',
            field=models.BooleanField(default=True),
        ),
    ]
