# Generated by Django 2.2.6 on 2019-10-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('show', '0002_auto_20191008_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preferred_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterInShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Character')),
                ('primary_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='cast.Actor')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Run')),
                ('understudy_actors', models.ManyToManyField(blank=True, related_name='understudy_characters', to='cast.Actor')),
            ],
        ),
    ]
