# Generated by Django 2.2.6 on 2019-10-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_auto_20191010_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterinshow',
            options={'ordering': ['run', 'character__character_type__ordering_prefernce', 'character__name', 'primary_actor']},
        ),
    ]
