# Generated by Django 2.2.6 on 2019-10-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0003_auto_20191010_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterinshow',
            options={'ordering': ['run', 'character__character_type__ordering_preference', 'character__name', 'primary_actor']},
        ),
    ]
