# Generated by Django 2.2.6 on 2019-10-12 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('show', '0018_auto_20191012_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microphone.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Microphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx_number', models.CharField(max_length=255)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microphone.MicModel')),
            ],
        ),
        migrations.CreateModel(
            name='MicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RxBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=255)),
                ('frequency_low_mhz', models.PositiveIntegerField()),
                ('frequency_high_mhz', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MicrophoneAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Character')),
                ('microphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microphone.Microphone')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Run')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Show')),
            ],
        ),
        migrations.AddField(
            model_name='microphone',
            name='rx_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microphone.RxBand'),
        ),
        migrations.AddField(
            model_name='microphone',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microphone.MicType'),
        ),
    ]
