# Generated by Django 2.2.6 on 2019-10-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microphone', '0002_microphoneassignment_fixed_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microphoneassignment',
            options={'ordering': ['show', 'run', 'microphone__rx_number', 'character__character_type__ordering_preference', 'character__billing_order']},
        ),
    ]
