# Generated by Django 4.1.3 on 2022-11-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microphone', '0003_auto_20191013_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microphone',
            options={'ordering': ['rx_number']},
        ),
    ]
